format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_virtual_gpu}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: blendFunc}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: APP_VGPU_SetBlend}
  - type: String
    attributes: {id: blitBuffFunc}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: APP_VGPU_BlitBuffer}
  - type: String
    attributes: {id: intfInit}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: APP_SW_VGPUInit}
  - type: String
    attributes: {id: setGlobalAlphaFunc}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: APP_VGPU_SetGlobalAlpha}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: gfx_driver_vgpu}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_legato}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gpu_driver}
- type: ElementPosition
  attributes: {x: '496', y: '309', id: le_gfx_virtual_gpu}
