format_version: v1.0
type: UniqueComponent
attributes: {id: sys_input}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: MaxListeners}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5'}
  - type: Boolean
    attributes: {id: RTOSEnabled}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_input, value: 'false'}
- type: ElementPosition
  attributes: {x: '552', y: '182', id: sys_input}
